package com.ironhack.stolen_name_trucking_company_homework_3.enums;

public enum ReportCommands {
    REPORT_LEAD_BY_SALESREP("REPORT LEAD BY SALESREP"),
    REPORT_OPP_BY_SALESREP("REPORT OPPORTUNITY BY SALESREP"),
    REPORT_CLOSE_W_BY_SALESREP("REPORT CLOSE-WON BY SALESREP"),
    REPORT_CLOSE_L_BY_SALESREP("REPORT CLOSE-LOST BY SALESREP"),
    REPORT_OPEN_BY_SALESREP("REPORT OPEN BY SALESREP"),
    REPORT_OPP_BY_PRODUCT("REPORT OPPORTUNITY BY PRODUCT"),
    REPORT_CLOSE_W_BY_PRODUCT("REPORT CLOSE-WON BY PRODUCT"),
    REPORT_CLOSE_L_BY_PRODUCT("REPORT CLOSE-LOST BY PRODUCT"),
    REPORT_OPEN_BY_PRODUCT("REPORT OPEN BY PRODUCT"),
    REPORT_OPP_BY_COUNTRY("REPORT OPPORTUNITY BY COUNTRY"),
    REPORT_CLOSE_W_BY_COUNTRY("REPORT CLOSE-WON BY COUNTRY"),
    REPORT_CLOSE_L_BY_COUNTRY("REPORT CLOSE-LOST BY COUNTRY"),
    REPORT_OPEN_BY_COUNTRY("REPORT OPEN BY COUNTRY"),
    REPORT_OPP_BY_CITY("REPORT OPPORTUNITY BY CITY"),
    REPORT_CLOSE_W_BY_CITY("REPORT CLOSE-WON BY CITY"),
    REPORT_CLOSE_L_BY_CITY("REPORT CLOSE-LOST BY CITY"),
    REPORT_OPEN_BY_CITY("REPORT OPEN BY CITY"),
    REPORT_OPP_BY_INDUSTRY("REPORT OPPORTUNITY BY INDUSTRY"),
    REPORT_CLOSE_W_BY_INDUSTRY("REPORT CLOSE-WON BY INDUSTRY"),
    REPORT_CLOSE_L_BY_INDUSTRY("REPORT CLOSE-LOST BY INDUSTRY"),
    REPORT_OPEN_BY_INDUSTRY("REPORT OPEN BY INDUSTRY"),
    MEAN_EMPCOUNT("MEAN EMPLOYEECOUNT"),
    MEDIAN_EMPCOUNT("MEDIAN EMPLOYEECOUNT"),
    MAX_EMPCOUNT("MAX EMPLOYEECOUNT"),
    MIN_EMPCOUNT("MIN EMPLOYEECOUNT"),
    MEAN_QUANT("MEAN QUANTITY"),
    MED_QUANT("MEDIAN QUANTITY"),
    MAX_QUANT("MAX QUANTITY"),
    MIN_QUANT("MIN QUANTITY"),
    MEAN_OPPS_PERR_ACC("MEAN OPPS PER ACCOUNT"),
    MED_OPPS_PERR_ACC("MEDIAN OPPS PER ACCOUNT"),
    MAX_OPPS_PERR_ACC("MAX OPPS PER ACCOUNT"),
    MIN_OPPS_PERR_ACC("MIN OPPS PER ACCOUNT"),
    MAIN_MENU("MAIN MENU"),
    QUIT("QUIT"),
    NONE("");

    public String value;

    private ReportCommands(String value) {
        this.value=value;
    }

    public static ReportCommands getCommandType(String cValue) {
        for (ReportCommands command: values()) {
            if(command.value.equals(cValue))
                return command;
        }
        return ReportCommands.NONE;
    }

}
